# Generated by Django 4.2.3 on 2023-10-20 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('idespecie', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('especie', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'especies',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('idturno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('dni', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'turnos',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('dni', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('idraza', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('raza', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'razas',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('dni', models.CharField(max_length=20)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idpaciente', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=10)),
                ('seniaspart', models.CharField(max_length=50)),
                ('chip', models.CharField(max_length=20)),
                ('fechana', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('dni', models.OneToOneField(db_column='dni', on_delete=django.db.models.deletion.CASCADE, to='app.persona')),
                ('idespecie', models.ForeignKey(db_column='idespecie', on_delete=django.db.models.deletion.CASCADE, to='app.especie')),
                ('idraza', models.ForeignKey(db_column='idraza', on_delete=django.db.models.deletion.CASCADE, to='app.raza')),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
        migrations.AddField(
            model_name='especie',
            name='idraza',
            field=models.ForeignKey(db_column='idraza', on_delete=django.db.models.deletion.CASCADE, to='app.raza'),
        ),
    ]
