# Generated by Django 4.2.3 on 2023-10-20 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_sesion_id_alter_sesion_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sesion',
            table='sesion',
        ),
    ]
