# Generated by Django 4.2.3 on 2023-10-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_especie_idespecie_alter_event_idturno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='chip',
            field=models.IntegerField(),
        ),
    ]
