# Generated by Django 4.2.3 on 2023-10-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_paciente_chip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='idturno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
