# Generated by Django 4.2.3 on 2023-11-04 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_event_idturno'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenCli',
            fields=[
                ('idexamenc', models.IntegerField(primary_key=True, serialize=False)),
                ('ganglios', models.CharField(max_length=20)),
                ('mucosas', models.CharField(max_length=20)),
                ('temperatura', models.CharField(max_length=20)),
                ('cardiaca', models.CharField(max_length=20)),
                ('pulso', models.CharField(max_length=20)),
                ('respiratoria', models.CharField(max_length=20)),
                ('laboratorio', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'idexamenc',
            },
        ),
        migrations.CreateModel(
            name='Peso',
            fields=[
                ('idpeso', models.IntegerField(primary_key=True, serialize=False)),
                ('peso', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'peso',
            },
        ),
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('idvacuna', models.IntegerField(primary_key=True, serialize=False)),
                ('vacuna', models.CharField(max_length=20)),
                ('laboratorio', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'vacuna',
            },
        ),
        migrations.CreateModel(
            name='historial',
            fields=[
                ('idhistorial', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('peso', models.CharField(max_length=50)),
                ('fechadesp', models.DateField()),
                ('proddesp', models.CharField(max_length=50)),
                ('lotev', models.CharField(max_length=100)),
                ('fechacelo', models.DateField()),
                ('fechapart', models.DateField()),
                ('est', models.CharField(max_length=10)),
                ('cons', models.CharField(max_length=10)),
                ('hall', models.CharField(max_length=10)),
                ('idexmanec', models.ForeignKey(db_column='idexamenc', on_delete=django.db.models.deletion.CASCADE, to='app.examencli')),
                ('idpaciente', models.ForeignKey(db_column='idpaciente', on_delete=django.db.models.deletion.CASCADE, to='app.paciente')),
                ('idpeso', models.ForeignKey(db_column='idpeso', on_delete=django.db.models.deletion.CASCADE, to='app.peso')),
                ('idvacuna', models.ForeignKey(db_column='idvacuna', on_delete=django.db.models.deletion.CASCADE, to='app.vacunas')),
            ],
            options={
                'db_table': 'idhistorial',
            },
        ),
    ]
