# Generated by Django 4.2.3 on 2023-12-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_examencli_peso_vacunas_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='idturno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
