# Generated by Django 4.2.3 on 2023-12-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_event_tipo_alter_event_email_alter_event_idturno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
