# Generated by Django 4.2.3 on 2023-12-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_event_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='celular',
            field=models.CharField(max_length=20),
        ),
    ]
