# Generated by Django 4.2.3 on 2023-12-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_event_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='celular',
            field=models.CharField(max_length=100),
        ),
    ]
