# Generated by Django 4.2.3 on 2024-01-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_event_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='idturno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='event',
            table=None,
        ),
    ]
