# Generated by Django 4.2.3 on 2024-01-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_event_idturno_alter_event_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='peso',
        ),
    ]
