# Generated by Django 4.2.3 on 2024-01-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_cons_historial_estirilizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunas',
            name='laboratorio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vacunas',
            name='vacuna',
            field=models.CharField(max_length=100),
        ),
    ]
