# Generated by Django 4.2.3 on 2024-01-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_vacunas_laboratorio_alter_vacunas_vacuna'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial',
            old_name='idexmanec',
            new_name='idexamenc',
        ),
        migrations.RemoveField(
            model_name='examencli',
            name='laboratorio',
        ),
        migrations.RemoveField(
            model_name='peso',
            name='fecha',
        ),
    ]
