# Generated by Django 4.2.3 on 2024-01-04 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_idexmanec_historial_idexamenc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peso',
            old_name='pesoT',
            new_name='peso',
        ),
    ]
