# Generated by Django 4.2.3 on 2024-01-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_pesot_peso_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peso',
            name='idpeso',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
