# Generated by Django 4.2.3 on 2024-01-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_historial_consulta_alter_historial_hallazgo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='consulta',
            field=models.TextField(default=''),
        ),
    ]
