# Generated by Django 4.2.3 on 2024-01-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_historial_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historial',
            name='fechacelo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historial',
            name='fechadesp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='historial',
            name='fechapart',
            field=models.DateField(),
        ),
    ]
