# Generated by Django 4.2.3 on 2024-01-09 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_historial_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.ForeignKey(db_column='dni', on_delete=django.db.models.deletion.CASCADE, to='app.persona'),
        ),
    ]
