# Generated by Django 4.2.3 on 2024-01-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_paciente_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='celular',
            field=models.CharField(max_length=255),
        ),
    ]
