# Generated by Django 4.2.3 on 2024-01-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_historial_idpaciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='idpaciente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
